name: Generate Manual GitHub Stats

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Generate SVG
        run: |
          python scripts/generate_manual_streak.py

      - name: Commit SVG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add profile/streak.svg

          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi

          git commit -m "Update custom GitHub stats"

          git pull --rebase origin main

          git push origin main
